name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check repo files
        run: ls -la cms  # cms qovluğunda nə var görmək üçün

      - name: Build backend jar
        run: |
          cd cms
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t agilazizovf/cms:latest cms

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push agilazizovf/cms:latest

      - name: Deploy to server
        run: |
          scp -i ${{ secrets.SERVER_KEY }} docker-compose.yml root@YOUR_SERVER_IP:/root/
          ssh -i ${{ secrets.SERVER_KEY }} root@YOUR_SERVER_IP 'docker compose -f /root/docker-compose.yml up -d'
