name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t agilazizovf/cms:latest .

      - name: Copy docker-compose.yml to server
        run: |
          scp -i ${{ secrets.SERVER_KEY }} docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/

      - name: Deploy on server
        run: |
          ssh -i ${{ secrets.SERVER_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'docker compose -f /home/${{ secrets.SERVER_USER }}/docker-compose.yml up -d'
