name: Deploy to Contabo

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'       # JDK version
          distribution: 'temurin'  # JDK distribution

      - name: Build with Maven
        run: |
          cd cms
          mvn clean package -DskipTests

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 194.163.173.179
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: cms/target/cms-0.0.1-SNAPSHOT.jar   # Full relative path from repo root
          target: /root/cms-0.0.1-SNAPSHOT.jar

      - name: Restart Spring Boot app
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 194.163.173.179
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart cms.service
            systemctl status cms.service
