name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn --version

      - name: Build with Maven (skip tests)
        run: |
         cd cms
         mvn clean package -DskipTests

      - name: Copy Docker Compose to server
        run: scp -i ${{ secrets.SERVER_KEY }} docker-compose.yml root@194.163.173.179:/root/

      - name: Restart Docker Compose on server
        run: ssh -i ${{ secrets.SERVER_KEY }} root@194.163.173.179 "docker compose -f /root/docker-compose.yml up -d"
